package app.models;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Mihkel on 14.10.2015.
 */
@Entity
@Table(name = "daily_entry")
public class DailyEntry {

    // Entity's fields (private)

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    @NotNull
    private Integer userId;

    @NotNull
    private Double relativePercentage;

    @NotNull
    private Integer amount;

    @NotNull
    private Double absoluteAmount;

    @NotNull
    private String date;


    // Public methods

    public DailyEntry() { }

    public DailyEntry(long id) {
        this.id = id;
    }

    public DailyEntry(Integer userId, Double relativePercentage, Integer amount, Double absoluteAmount, String date) {
        this.userId = userId;
        this.relativePercentage = relativePercentage;
        this.amount = amount;
        this.absoluteAmount = absoluteAmount;
        this.date = date;
    }

    public Integer getUserId() {
        return userId;
    }

    public Double getRelativePercentage() {
        return relativePercentage;
    }

    public Integer getAmount() {
        return amount;
    }

    public Double getAbsoluteAmount() {
        return absoluteAmount;
    }

    public String getDate() {
        return date;
    }
}
